version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    docker:
      - image: circleci/golang:1
    working_directory: /go/src/github.com/martinsirbe/go-sms
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
      - run: make lint
      - run: make test
      - codecov/upload:
          file: coverage.txt
      - run: make build
